### ISSUE TITLE
[enhancement] JSON5 Support

### ISSUE THREAD

**Issue by CelticParser** [joshswan/gulp-merge-json#13]
Added support for [JSON5](https://github.com/json5/json5) would allow lots of extra goodies for the  files being merged/combined.

> **e.g.** We like to use `comments`, `TODO`'s, and `FIXME`'s in our `json` (`json5`) files and use [gulp-todo](https://github.com/pgilad/gulp-todo) as a reporter to a `TODO.md` ).

I believe this could be beneficial to Hugo and it's users.

**Comment by joshswan** [comment]
Happy to accept a PR for this. I'm quite busy at the moment so it'll be a bit before I can look into it myself.

**Comment by joshswan** [comment]
Should work on `master` now. Enabled by settings `json5: true` in the options object. Check out the tests for more info.

**Comment by CelticParser** [comment]
Awesome!
