### ISSUE TITLE
merge json array

### ISSUE THREAD

**Issue by jbouzekri** [joshswan/gulp-merge-json#14]
If I try to merge 2 json arrays. Let's say I have 2 arrays with 2 objects in each. 

```
[ { ... }, { ... } ]
[ { ... }, { ... } ]
```

I get something like that : 

```
{
    "0": { ... },
    "1": { ... }
}
```

It outputs an object and not an array and this object is using the array index as property so I only get the last 2 object of my arrays.

**Comment by joshswan** [comment]
By default, parsed JSON is merged into an empty object. You can pass an empty array as the starting value to override this (e.g. `pipe(merge('combined.json', false, []))`). That should work, but feel free to submit a PR if you can think of a better way of dealing with this.

**Comment by jbouzekri** [comment]
Finally I chose another plugin and I tweak it a bit to match my needs : https://github.com/Itrulia/gulp-concat-json

Your solution did not work. I tried to set concatArray to true too but the problem is in the lodash `mergeWith` function.

If the parameter `a` is an empty array (startObj), the value passed to the customizer callback is `undefined` so it does not execute the union.

**Comment by joshswan** [comment]
The fix I suggested works just fine with regard to the issue you reported above. If passed an empty array as a `startObj`, the result is not an object with array keys as object keys, but rather an array with merged objects. I've added another test to demonstrate.

**Comment by jbouzekri** [comment]
@joshswan : I think you misunderstood. What works is that my example in the first comment generates an array with 2 items where these items are the merged object. But if we merge these 2 arrays, don't you think that it should generate an array with 4 items ? `[ { ... }, { ... }, { ... }, { ... } ]`

**Comment by joshswan** [comment]
Yeah that's a good point. I've just pushed another update that should enable this result given an empty array `startObj` and `concatArrays` enabled. You can try it out on `master` if you're interested.

**Comment by jbouzekri** [comment]
it seems nice. I will check it this evening.

**Comment by jbouzekri** [comment]
Worked like a charm ^^. Thank you @joshswan .
