### ISSUE TITLE
Merging multiple files keeps only keys from last file in array

### ISSUE THREAD

**Issue by vuk** [joshswan/gulp-merge-json#18]
I have 3 json files 

- config.json
-- config-dev.json
-- config-dev-locale.json

So what I did was adding 

```javascript
return gulp.src(['config.json', 'config-dev.json', 'config-dev-locale.json'])
       // gulp.src would return files in incosistent order thus using merge plugin https://www.npmjs.com/package/gulp-order
      .pipe(order([
        'config.json',
        'config-dev.json',
        'config-dev-locale.json'
      ]))
      .pipe(merge({
        fileName: 'resulting-config.json',
        contactArrays: true,
        mergeArrays: true
      }))
      .pipe(gulp.dest('./app'));
```

So this would actually only return the last file in order in this case config-dev-locale.json

Idea was to have majority of config in config.json and override it with -dev and -dev-locale files with only several keys that differ from original files, but it only returns last file that is in order

This also happens if I comment out `order` part

**Comment by joshswan** [comment]
Hm. You're going to have to give me some idea of what data is going in and what's coming out. The way this plugin works is by parsing the contents of the files, merging each into an single object and then stringifying, so as long as all the data is getting in, you should be getting the merged result.

**Comment by vuk** [comment]
Let's say first file is `config.json`

```javascript
{
    "APPLICATION_NAME": "Test",
    "OPTIONS": [
        "option1",
        "option2",
        "option3"
    ],
    "SETTINGS": {
        "SETTING1": "setting1",
        "SETTING2": 1000,
    }
    "ENVIRONMENT": "Development"
}
```

And second file should override `ENVIRONMENT` key, so it only has that key

```javascript
{
    "ENVIRONMENT": "Production"
}
```

Could it be an issue that it uses array?

**Comment by joshswan** [comment]
Using the following gulp task (from yours above):
```javascript
return gulp.src(['config.json', 'config-prod.json'])
      .pipe(merge({
        fileName: 'resulting-config.json',
        contactArrays: true,
        mergeArrays: true
      }))
      .pipe(gulp.dest('./'));
```
And the JSON from your previous comment in `config.json` and `config-prod.json`, respectively, my resulting JSON file is:
```JSON
{
	"APPLICATION_NAME": "Test",
	"OPTIONS": [
		"option1",
		"option2",
		"option3"
	],
	"SETTINGS": {
		"SETTING1": "setting1",
		"SETTING2": 1000
	},
	"ENVIRONMENT": "Production"
}
```
Which seems correct
