### ISSUE TITLE
Still problem with array merging

### ISSUE THREAD

**Issue by sadiqhabib** [joshswan/gulp-merge-json#19]
// Sample one
{ "tags": [{"name": "store"} ] }
// Sample two
{ "tags": [{"name": "store2"} ] }
// Sample three
{ "tags": [{"name": "store3"} ] }

// Exacted result
{ "tags": [{"name": "store"}, {"name": "store2"}, {"name": "store3"}] }

//Got this
{ "tags": [{"name": "store3"} ] }

**Comment by joshswan** [comment]
What options are you using? This should work as expected with `concatArrays` enabled

**Comment by sadiqhabib** [comment]
Yes i tried `mergeArrays: true` still same result

**Comment by joshswan** [comment]
`concatArrays` and `mergeArrays` both need to be `true` for this behavior. `mergeArrays` defaults to `true` but `concatArrays` does not. 

I know it's a bit confusing. I'm still trying to think of a better way to map the different behaviors to clearer options.

**Comment by sadiqhabib** [comment]
It works amazingly thanks.
