### ISSUE TITLE
Passing multiple arguments is deprecated! Pass an options object instead.

### ISSUE THREAD

**Issue by mortennh** [joshswan/gulp-merge-json#20]
When i take your example code:

```Javascript
gulp.src('jsonFiles/**/*.json')
    .pipe(merge())
    .pipe(gulp.dest('./dist'));
```

I get this Warning: 

```
WARNING!!
Passing multiple arguments is deprecated! Pass an options object instead.
```

**Comment by joshswan** [comment]
Oops, the deprecation warning is a little overzealous and shouldn't be saying anything when you pass no options at all. Should be fixed in v1.0.1 that I just published.

Thanks for pointing this out!
