### ISSUE TITLE
ConcatArrays option returns duplicated items

### ISSUE THREAD

**Issue by nosir** [joshswan/gulp-merge-json#24]
Hey, firstly, thanks for the great lib.

I know this is not an actual issue but, I am merging these 2 json:
a: 
```
 ...
  "key": [
    "value_1"
  ]
}
```

b: 
```
...
  "key": [
    "value_1",
    "value_2"
  ]
}
```

What I want to achieve is:
```
...
  "key": [
    "value_1",
    "value_2"
  ]
}
```

While with this lib it seems only does concat and returns:
```
...
  "key": [
    "value_1",
    "value_1",
    "value_2"
  ]
}
```

If you think this is okay to have an extra `uniqArray` option, I'd happy to send a PR.

Cheers

**Comment by nosir** [comment]
Or maybe not to have that `uniq` option, only when `concatArrays` and `mergeArrays` both are true, it returns a concatenated array with uniq items here:
https://github.com/joshswan/gulp-merge-json/blob/master/index.js#L25

**Comment by joshswan** [comment]
I would say that this is expected with `concatArrays` as you say, and I'm a little hesitant to add more options or make them more complicated. I'd say this is a good use case for the `customizer` option. I just added another example to the README with an example that should give concatenated arrays with unique values only.

**Comment by nosir** [comment]
Nice solution, thanks for the quick updating!
