### ISSUE TITLE
Vinyl File type reference is broken

### ISSUE THREAD

**Issue by qtiki** [joshswan/gulp-merge-json#26]
The Vinyl File type import is broken: https://github.com/joshswan/gulp-merge-json/blob/6a36ea30341d5c64cb5b2593323b9e5b668906ff/index.d.ts#L2

TypeScript compiler throws the following error: `node_modules/gulp-merge-json/index.d.ts(2,12): error TS2305: Module '.../node_modules/@types/vinyl/index"' has no exported member 'File'`

Changing the import to `import * as File from 'vinyl'` fixes the issue.

Tested with:
* `gulp-merge-json` v1.2.1
* `@types/vinyl` v2.0.2
* `typescript` v2.7.2

**Comment by joshswan** [comment]
Just published `v1.2.2` with the fix. Thanks for pointing this out

**Comment by qtiki** [comment]
Confirmed it works now with `v1.2.2` from npm! 👍
