### ISSUE TITLE
Generated Json File Format and Content is Incorrect

### ISSUE THREAD

**Issue by SharkBaby** [joshswan/gulp-merge-json#30]
when I use this npm module to merge two json, I found some of the json file format is incorrect, and some content also is missing, Is there anyone help me?
**CODE**
![image](https://user-images.githubusercontent.com/18545909/56405688-fae2cb00-629f-11e9-8885-d86bb6d63594.png)
**format is incorrect**
![image](https://user-images.githubusercontent.com/18545909/56405708-14841280-62a0-11e9-99b6-934e98014af2.png)

**Comment by joshswan** [comment]
At first glance, it looks like there's something else involved here. I'd recommend checking your input files and starting object and removing any other steps that could be affecting the output.

If you'd like further help, please share the input files and starting object you're using.

**Comment by SharkBaby** [comment]
sorry, it is one mistake by me, the json **concatCssJsJson** formed incorrectly by me.
so my recommnedation is we need to debug and find the root cause quickly.thanks
