### ISSUE TITLE
Yet another array merging issue: root node array

### ISSUE THREAD

**Issue by noraj** [joshswan/gulp-merge-json#32]
I'm seen most of the issues are related to merging arrays but yet I didn't find the solution reading them.

## The issue: root node array

root node array is not merging properly like is does when it's a sub-node array

file1.json

```json
[
  {"title": "A"},
  {"title": "B"}
]
```

file2.json

```json
[
  {"title": "C"},
  {"title": "D"}
]
```

expected result

```json
[
  {"title": "A"},
  {"title": "B"},
  {"title": "C"},
  {"title": "D"}
]
```

with the 4 possible combinations of `concatArrays,` + `mergeArrays`

concatArrays | mergeArrays | output
---|---|---
true | true | ❌ 
true | false | ❌
false | true | ❌
false | false | ❌

```json
{
  "0": {
    "title": "C"
  },
  "1": {
    "title": "D"
  }
}
```

## Similar but not exactly the same issues

- #19, #22, #18, #11 the array there is an element not the root node

## Working example of sub-node array

file1.json

```json
{
  "array": [
    {"title": "A"},
    {"title": "B"}
  ]
}
```

file2.json

```json
{
  "array": [
    {"title": "C"},
    {"title": "D"}
  ]
}
```

`concatArrays: true` + `mergeArrays: true`

```json
{
  "array": [
    {
      "title": "A"
    },
    {
      "title": "B"
    },
    {
      "title": "C"
    },
    {
      "title": "D"
    }
  ]
}
```

**Comment by joshswan** [comment]
You need to override the `startObj` for root level arrays or it attempts to merge those arrays into the default starting object: `{}`. There's a test case that covers this scenario and looks like:

```javascript
gulp.src(['test/json/array1.json', 'test/json/array2.json']).pipe(merge({
  startObj: [],
}));
```

Let me know if you have further issues and happy to accept a PR for improving the docs if needed :)

**Comment by noraj** [comment]
@joshswan Thanks.
