### ISSUE TITLE
Please update json5 lib to fix minimist sec vun

### ISSUE THREAD

**Issue by cameronbosnic** [joshswan/gulp-merge-json#33]
It looks like there have been a few updates to the json5 library, the latest being 2.2.1 that addresses a security vunerability with minimist (by removing it https://github.com/json5/json5/commit/502da86f8e8e2168e301dc5157919935082d0f7b) as well as some other bug fixes since 2.1.3 .

**Comment by cameronbosnic** [comment]
https://github.com/joshswan/gulp-merge-json/pull/34

**Comment by joshswan** [comment]
Released v2.1.2 on npm
